/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.3-45-g2d6ee37238-20260427"
#endif /* AVUTIL_FFVERSION_H */
